services:
  ros2-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ros2dev
        USER_UID: 1001
        USER_GID: 1001
    container_name: ros2-jazzy-dev
    volumes:
      # Mount your source code for live editing
      - ./src:/ros2_ws/src
      # Mount for X11 forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Persistent bash history
      - ros2_bash_history:/home/ros2dev/.bash_history_volume
    environment:
      - DISPLAY=${DISPLAY}
      - HISTFILE=/home/ros2dev/.bash_history_volume/.bash_history
    network_mode: host
    stdin_open: true
    tty: true
    working_dir: /ros2_ws
    user: "1001:1001"

volumes:
  ros2_bash_history:
