services:
  ros2-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2-${PROJECT_NAME:-default}-dev
    volumes:
      - ./src:/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    stdin_open: true
    tty: true
    working_dir: /ros2_ws
    user: "${USER_UID:-1000}:${USER_GID:-1000}"
